### PR TITLE
add component.json

### PR DESCRIPTION
**Pull request by slang800**
for http://component.github.io/ & http://duojs.org/

### CODE REVIEW

**Comment by nlf** [comment]
can you merge master into this, fix the version, and update the pull request to make sure travis passes?

**Comment by slang800** [comment]
ok, all set!

**Comment by nlf** [comment]
your version field is still wrong

**Comment by slang800** [comment]
agh... ok, should be fixed now

**Comment by nlf** [comment]
does this require publishing to another service? i'm not familiar with component or duojs

**Comment by slang800** [comment]
nope, they use github for everything

**Pull request merged**
