### PR TITLE
No equal sign

### PR DESCRIPTION
**Pull request by pierot**
Pull request for functionality described here: https://github.com/hapijs/qs/issues/79#issuecomment-103473308

### CODE REVIEW

**Comment by scharf** [comment]
Looks good, but I am afraid this change will break a lot of existing code. I think it would be best to hide this feature behind an option (like `strictNullHandling`)

**Comment by tunnckoCore** [comment]
> I think it would be best to hide this feature behind an option

:+1:

**Comment by nlf** [comment]
This definitely needs to be behind an option

**Comment by pierot** [comment]
I updated the PR with the option `strictNullHandling`.

**Pull request merged**
